---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fileshare-sa
  namespace: ctf-challenge

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ctf-challenge
  name: secret-reader
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: ctf-challenge
subjects:
  - kind: ServiceAccount
    name: fileshare-sa
    namespace: ctf-challenge
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cross-namespace-secrets
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list']
    resourceNames: ['tls-certificates']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cross-namespace-binding
subjects:
  - kind: ServiceAccount
    name: fileshare-sa
    namespace: ctf-challenge
roleRef:
  kind: ClusterRole
  name: cross-namespace-secrets
  apiGroup: rbac.authorization.k8s.io
